---
title: "JSC370 Lab 12"
author: "Shijun Yu"
output: 
    html_document:
        toc: TRUE
        toc_float: TRUE
---

<br>

This is my JSC370 Lab 12 website.

<br>

```{r setup, message=FALSE, echo=FALSE, warning=FALSE}

library(data.table)
library(tidyverse)
library(dplyr)
library(plotly)
library(DT)
library(knitr)
library(widgetframe)

# Initialize code chunk options
opts_chunk$set(
  warning = FALSE,
  message = FALSE,
  eval=TRUE,
  echo = TRUE,
  cache = FALSE,
  fig.width = 7, 
  fig.align = 'center',
  fig.asp = 0.618,
  out.width = "700px",
  class.source = "code-r")
```

```{css, echo = FALSE}
.code-r { /* Code block */
  font-size: 15px;
}

.code-r-small { /* Code block */
  font-size: 10px;
}
```

<br>

```{r load-data, echo=FALSE}
source("process_starbucks_data.R")
```

## Showcasing plots {.tabset}

### Figure 1

```{r p1, echo=FALSE}
p2<-ggplot(sb_nutr, aes(x=Calories, fill=Category )) + 
  geom_histogram(alpha = 0.5)+
  theme_bw()

ggplotly(p2)
```

### Figure 2

```{r p2, echo=FALSE}
sb_nutr_long <- sb_nutr |>
  unnest_tokens(word, Item, token = "words") |>
  filter(word %in% topwords$word) |>
  pivot_longer(cols = c(Calories, `Fat (g)`, `Carb. (g)`, `Fiber (g)`, `Protein (g)`), 
               names_to = "Nutrient", values_to = "Value")
plot_ly(data = sb_nutr_long, 
        x = ~word, 
        y = ~Value, 
        color = ~Nutrient, 
        type = "box") |>
  layout(
    title = "Nutritional Values of Starbucks Items by Top 10 Words",
    xaxis = list(title = "Item Word"),
    yaxis = list(title = "Nutritional Value"),
    boxmode = "group"
  )

```

## {-}

<br>

